---
title: "state_correlations"
author: "Arushi Saxena"
date: "4/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(reprex)
library(gt)
library(infer)
library(purrr)
library(skimr)
library(broom)
library(ggpubr) #To show correlation coefficient on the plots 
```

```{r} 
# Read in the google search term popularity by state (from 3/11/20 - 3/29/20)

all_searches <- read_csv("Shiny_app/google_search_geo.csv",col_types = cols())
all_searches
socialdistance_march_F

# Quick data exploration to see distribution of social distancing scores by state
summary(socialdistance_march_F)
socialdistance_march_F %>%
  ggplot(aes(x=average)) + geom_histogram()

# Need to pivot wider the search data so we can join it with social distancing data and do a scatterplot by state 

all_searches2 <- all_searches %>%
  pivot_wider(names_from = term, values_from = search_term_popularity)

# Inner join the social distancing data with the google search data

joined_data <- all_searches2 %>%
  inner_join(socialdistance_march_F, by = c("State" = "state"))

# Make a table with state abbreviations to join with consolidated data. Will plot the state names on my scatterplot

state_info <- tibble(StateName=state.name, Abb=state.abb) %>%
  add_row(StateName = "District of Columbia", Abb = "DC")

# Join the state_info with consolidated data. I'll actually make the scatterplots in my app.R page

joined_dataF <- joined_data %>%
  left_join (state_info, by = c("State" = "StateName"))

saveRDS(joined_dataF, file = "joined_dataF.rds")

# Test plotting of the scatterplot. I won't use this for Shiny, this is just a test visual.

coronavirus <- joined_dataF %>%
  ggplot(aes(x=average, y=`coronavirus`, label=Abb)) + geom_point() +theme_classic() + theme(axis.text.x = element_text(angle = 45)) + labs(x="Social Distancing Score", y="Search Term Popularity: 'Coronavirus'") + scale_x_reverse() + geom_smooth(method = "glm", se = FALSE, color = "black") + stat_cor(method="pearson", label.x = 5, label.y = 110) + geom_text(check_overlap = FALSE, nudge_x = 0.05, nudge_y = 1, size = 3)


```

