---
title: "toptweet_table"
author: "Arushi Saxena"
date: "4/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(DT)
#install.packages("DT")
```

```{r}
# Make a table of all tweets
lib <- read_csv("Shiny_app/tweets_0412_v2.csv")

# Make a table for each of the common words
false <- lib %>%
  select(text, favorite_count, retweet_count) %>%
  filter(str_detect(text,"false")==TRUE) %>%
  mutate(term = "false")

photo <- lib %>%
  select(text, favorite_count, retweet_count) %>%
  filter(str_detect(text,"photo")==TRUE) %>%
  mutate(term = "photo")

trump <- lib %>%
  select(text, favorite_count, retweet_count) %>%
  filter(str_detect(text,"trump")==TRUE) %>%
  mutate(term = "trump")

love <- lib %>%
  select(text, favorite_count, retweet_count) %>%
  filter(str_detect(text,"love")==TRUE) %>%
  mutate(term = "love")

# Combine all table into one top tweets table
toptweets <- rbind(false,photo,trump,love) %>%
  rename(`Tweet Text` = text, `Favorites` = favorite_count, 'Retweets' = retweet_count)
  

toptweets
```

